CREATE TABLE Accounts(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    IBAN VARCHAR(50),
    BBAN VARCHAR(50),
    accountType VARCHAR(30)
);

CREATE UNIQUE INDEX Account_IBAN
ON Accounts(IBAN);